# Generated by Django 4.2 on 2023-04-28 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dukaan', '0007_alter_dukan_user_media_alter_dukan_user_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop_category',
            fields=[
                ('s_id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.TextField(blank=True, null=True)),
                ('add_date_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('media', models.ImageField(blank=True, null=True, upload_to='media')),
            ],
        ),
    ]
